### ISSUE TITLE
"with-plugin" doesn't work without a trailing slash for the dest folder

### ISSUE THREAD

**Issue by LaurentGoderre** [assemble/grunt-assemble-i18n#23]
Currently, if the trailing slash is omitted, all files are written to the same file

For example 

```
theme:
  options:
    plugins: ['assemble-contrib-i18n']
      i18n:
        data: ['site/data/i18n.json']
        templates: ['site/pages/theme/*.hbs']
  dest:  "dist/unmin/theme"
  src: "!*.*"
```

Results in all files being written to `dist/unmin/theme.html`
